### ISSUE TITLE
Take photo and select gallery photo issue

### ISSUE THREAD

**Issue by comeback4u** [AleBarreto/FirebaseAndroidChat#1]
FATAL EXCEPTION: main
                                                                            Process: alessandro.firebaseandroid, PID: 13440
                                                                            java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://media/external/images/media/4879 flg=0x1 (has extras) }} to activity {alessandro.firebaseandroid/alessandro.firebaseandroid.MainActivity}: java.lang.IllegalArgumentException: The supplied bucketname is not available to this project.
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:4920)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
                                                                                at android.app.ActivityThread.access$1600(ActivityThread.java:221)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:158)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
                                                                             Caused by: java.lang.IllegalArgumentException: The supplied bucketname is not available to this project.
                                                                                at com.google.android.gms.common.internal.zzab.zzb(Unknown Source)
                                                                                at com.google.firebase.storage.FirebaseStorage.zzx(Unknown Source)
                                                                                at com.google.firebase.storage.FirebaseStorage.getReferenceFromUrl(Unknown Source)
                                                                                at alessandro.firebaseandroid.MainActivity.onActivityResult(MainActivity.java:104)
                                                                                at android.app.Activity.dispatchActivityResult(Activity.java:7137)
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963) 
                                                                                at android.app.ActivityThread.access$1600(ActivityThread.java:221) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:158) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

**Comment by AleBarreto** [comment]
In class Util change
public static final String URL_STORAGE_REFERENCE = "gs://alefirebase-b6a81.appspot.com";
to  storage reference = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx";

**Comment by comeback4u** [comment]
Yaa its working. Thanx.

**Comment by android91ankit** [comment]
hi , i used your code i am getting same error can you tell me which storage reference you are talking about , also does there any  user limit in using Firebase chat ?
