### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by malikmotani** [AleBarreto/FirebaseAndroidChat#12]
11-30 11:22:29.106 5465-5873/alessandro.firebaseChat E/StorageException: StorageException has occurred.
                                                                         An unknown error occurred, please check the HTTP result code and inner exception for server response.
                                                                          Code: -13000 HttpResult: 400
11-30 11:22:29.106 5465-5873/alessandro.firebaseChat E/StorageException: The server has terminated the upload session
                                                                         java.io.IOException: The server has terminated the upload session
                                                                             at com.google.firebase.storage.UploadTask.zzcyp(Unknown Source)
                                                                             at com.google.firebase.storage.UploadTask.zzcyo(Unknown Source)
                                                                             at com.google.firebase.storage.UploadTask.run(Unknown Source)
                                                                             at com.google.firebase.storage.StorageTask$5.run(Unknown Source)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                             at java.lang.Thread.run(Thread.java:856)
11-30 11:22:29.114 5465-5465/alessandro.firebaseChat E/MainActivity: onFailure sendFileFirebase An unknown error occurred, please check the HTTP result code and inner exception for server response.

**Comment by doanngoctu95** [comment]
Hey i also make this problem like you, i want to know have you fixed it? and if ok, can you tell me how to fix it? tks so much!!!

**Comment by doanngoctu95** [comment]
i've just fixed it, I add permission : WRITE_EXTERNAL_STORAGE
and change TouchImageView into TouchImageView of my project.

**Comment by MuniraAwadh** [comment]
i have the same problem, what is the solution?

**Comment by equilizer** [comment]
please help same problem

**Comment by R33N4K0R** [comment]
add this to manifestfile <uses-permission
android:name="android.permission.WRITE_EXTERNAL_STORAGE"
/>


R33N4

**Comment by MuniraAwadh** [comment]
I wrote it from start connected firebase with my app, but I don't know what is the problem!

On Aug 23, 2017, at 10:58 AM, ReenaKoR <notifications@github.com<mailto:notifications@github.com>> wrote:

add this to manifestfile <uses-permission
android:name="android.permission.WRITE_EXTERNAL_STORAGE"
/>


R33N4

**Comment by fritexvz** [comment]
Your app should be compatible with Android OS 5.1 and newer, because you cannot read/write internal & external storage.

More on:
http://syncthing/syncthing-android#29

Android 4.0, 4.1, 4.2, 4.3, 4.4 and even 5.0 are affected by the issue of Google, not having an option to change the permission for your application.

You cannot even call the request for permission, because it does not exist as is in the stated Android OS versions, while changing the android manifest.xml file does not help either.

Regarding the HTTP error from Firebase, did you copy the right Storage Bucket parameter/URL to the app?
What kind of Storage rules are you using?
Try with these one:
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth!=null;
    }
  }
}
```
