### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by FRANKDUFF** [AleBarreto/FirebaseAndroidChat#8]
FATAL EXCEPTION: main
                                                                                       Process: com.keytoisro.gatemechanicalengineering, PID: 2728
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.keytoisro.gatemechanicalengineering/com.keytoisro.gatemechanicalengineering.ChatMainActivity}: java.lang.NullPointerException
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
                                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:166)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5584)
                                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                                        Caused by: java.lang.NullPointerException
                                                                                           at com.keytoisro.gatemechanicalengineering.ChatMainActivity.verificaUsuarioLogado(ChatMainActivity.java:335)
                                                                                           at com.keytoisro.gatemechanicalengineering.ChatMainActivity.onCreate(ChatMainActivity.java:95)
                                                                                           at android.app.Activity.performCreate(Activity.java:5447)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
                                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:166) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5584) 
                                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                                           at dalvik.system.NativeStart.main(Native Method) 
10-06 08:23:44.895 2728-2783/com.keytoisro.gatemechanicalengineering W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.

**Comment by saraljain12** [comment]
will you please share your code
